// Package playground holds the worked examples the browser playground opens
// with, and generates the file the page loads them from.
//
// They are kept here, in Go, rather than written by hand into JavaScript for one
// reason: the outputs are produced by the same compiler the page runs, so an
// example cannot claim a translation the tool does not actually perform.
// TestGeneratedExamplesAreCurrent fails when web/examples.js drifts from what
// the compiler produces today, which is what makes the seeded results on first
// paint trustworthy rather than decorative.
package playground

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"

	"github.com/polyql/polyql/pkg/compiler"
	"github.com/polyql/polyql/pkg/registry"
)

// Example is one entry in the playground's example list.
type Example struct {
	// Title is the label on the chip, and Note says what the example is for —
	// why a reader should care about this one rather than the next.
	Title string `json:"title"`
	Note  string `json:"note"`

	Source string `json:"source"`
	Target string `json:"target"`
	Query  string `json:"query"`

	// Result is the translation, filled in at generation time. The page renders
	// it immediately, before the WebAssembly module has finished loading, and
	// replaces it with a live translation once it has.
	Result json.RawMessage `json:"result,omitempty"`
}

// Examples are chosen to show the range of the tool honestly: what translates
// exactly, what translates approximately, and what the target genuinely cannot
// express. A list of only the successes would misrepresent the project, and the
// reports are the more interesting half of what it does.
func Examples() []Example {
	return []Example{
		{
			Title:  "Rate and sum",
			Note:   "The common case: the shape survives, the metric name becomes a label.",
			Source: "promql", Target: "logql",
			Query: `sum by (job) (rate(http_requests_total{env="prod"}[5m]))`,
		},
		{
			Title:  "Quantile over a histogram",
			Note:   "A PromQL function with no LogQL counterpart. Reported, not faked.",
			Source: "promql", Target: "logql",
			Query: `histogram_quantile(0.99, sum by (le) (rate(request_duration_seconds_bucket[5m])))`,
		},
		{
			Title:  "Offset with no range",
			Note:   "LogQL hangs an offset on a range and has no bare instant vector.",
			Source: "promql", Target: "logql",
			Query: `http_requests_total offset 1h`,
		},
		{
			Title:  "Log lines to a metric",
			Note:   "The line filter has nowhere to go in PromQL; the aggregation survives.",
			Source: "logql", Target: "promql",
			Query: `sum by (level) (rate({app="api"} |= "error" [5m]))`,
		},
		{
			Title:  "Span attributes to streams",
			Note:   "Scoped attributes folded onto LogQL's one flat namespace.",
			Source: "traceql", Target: "logql",
			Query: `{resource.service.name = "web" && span.http.method = "GET"}`,
		},
		{
			Title:  "A comparison the braces can't hold",
			Note:   "Not droppable and not a selector matcher — it becomes a filter stage.",
			Source: "traceql", Target: "logql",
			Query: `{resource.service.name = "web" && duration > 100ms}`,
		},
		{
			Title:  "An OR that is set membership",
			Note:   "Alternatives for one attribute are an IN, which both targets can write.",
			Source: "traceql", Target: "logql",
			Query: `{resource.service.name = "web" || resource.service.name = "api"}`,
		},
		{
			Title:  "A trace-tree relationship",
			Note:   "No log or metric query records which record is whose parent.",
			Source: "traceql", Target: "logql",
			Query: `{resource.service.name = "web"} >> {status = error}`,
		},
		{
			Title:  "Metric to span attributes",
			Note:   "A metric aggregation loses its name and temporal window; spans have no such concepts.",
			Source: "promql", Target: "traceql",
			Query: `sum by (job) (rate(http_requests_total{env="prod"}[5m]))`,
		},
	}
}

// Generate returns the contents of web/examples.js: the example list with each
// translation already run.
//
// It is a plain assignment rather than a module so the page can load it with an
// ordinary script tag and have the examples present before first paint — a
// playground that opened empty while it fetched its own examples would be a
// worse first impression than one that opened full.
func Generate(reg *registry.Registry) ([]byte, error) {
	examples := Examples()
	for i := range examples {
		result, err := translateExample(reg, examples[i])
		if err != nil {
			return nil, fmt.Errorf("example %q: %w", examples[i].Title, err)
		}
		examples[i].Result = result
	}

	body, err := json.MarshalIndent(examples, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encoding examples: %w", err)
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by internal/playground. DO NOT EDIT.\n")
	out.WriteString("//\n")
	out.WriteString("// Regenerate with `make generate`. Each result below was produced by the same\n")
	out.WriteString("// compiler the page runs, so the seeded output shown before the WebAssembly\n")
	out.WriteString("// module loads is the output the module will produce.\n")
	out.WriteString("window.POLYQL_EXAMPLES = ")
	out.Write(body)
	out.WriteString(";\n")
	return out.Bytes(), nil
}

// translateExample runs one example and shapes the result the way the browser
// build shapes a live one, so the page has a single rendering path for both.
func translateExample(reg *registry.Registry, ex Example) (json.RawMessage, error) {
	res, err := compiler.Translate(context.Background(), compiler.Request{
		SourceDSL: ex.Source,
		TargetDSL: ex.Target,
		Query:     ex.Query,
		Registry:  reg,
	})
	if err != nil {
		return nil, err
	}

	report := res.Report
	nodes := make([]map[string]any, 0, len(report.Nodes))
	for _, n := range report.Nodes {
		nodes = append(nodes, map[string]any{
			"path":   n.Path,
			"type":   n.NodeType,
			"flag":   n.Flag.String(),
			"reason": n.Reason,
		})
	}

	reportValue := map[string]any{
		"score":       report.FidelityScore,
		"total":       report.TotalNodes,
		"full":        report.FullCount,
		"partial":     report.PartialCount,
		"unsupported": report.UnsupportedCount,
		"worstFlag":   report.WorstFlag.String(),
		"worstReason": report.WorstReason,
		"summary":     report.Summary,
		"nodes":       nodes,
	}
	if report.SignalMismatch != nil {
		reportValue["signalMismatch"] = report.SignalMismatch.Message
	}

	return json.Marshal(map[string]any{
		"ok":     true,
		"output": res.Output,
		"text":   res.Text,
		"notes":  res.Notes,
		"report": reportValue,
	})
}
