// Code generated by internal/playground. DO NOT EDIT.
//
// Regenerate with `make generate`. Each result below was produced by the same
// compiler the page runs, so the seeded output shown before the WebAssembly
// module loads is the output the module will produce.
window.POLYQL_EXAMPLES = [
  {
    "title": "Rate and sum",
    "note": "The common case: the shape survives, the metric name becomes a label.",
    "source": "promql",
    "target": "logql",
    "query": "sum by (job) (rate(http_requests_total{env=\"prod\"}[5m]))",
    "result": {
      "notes": [
        "the metric name \"http_requests_total\" became a __name__ label matcher; LogQL selects streams by label only"
      ],
      "ok": true,
      "output": "sum by (job) (rate({__name__=\"http_requests_total\", env=\"prod\"}[5m]))",
      "report": {
        "full": 7,
        "nodes": [
          {
            "flag": "PARTIAL",
            "path": "Query",
            "reason": "NaN-as-sentinel semantics differ between promql and logql; absent-data handling may vary",
            "type": "Query"
          }
        ],
        "partial": 1,
        "score": 0.875,
        "signalMismatch": "query is METRIC, target supports LOG",
        "summary": "8 nodes: 7 full, 1 partial, 0 unsupported (score: 0.88)",
        "total": 8,
        "unsupported": 0,
        "worstFlag": "PARTIAL",
        "worstReason": "NaN-as-sentinel semantics differ between promql and logql; absent-data handling may vary"
      },
      "text": "# the metric name \"http_requests_total\" became a __name__ label matcher; LogQL selects streams by label only\nsum by (job) (rate({__name__=\"http_requests_total\", env=\"prod\"}[5m]))"
    }
  },
  {
    "title": "Quantile over a histogram",
    "note": "A PromQL function with no LogQL counterpart. Reported, not faked.",
    "source": "promql",
    "target": "logql",
    "query": "histogram_quantile(0.99, sum by (le) (rate(request_duration_seconds_bucket[5m])))",
    "result": {
      "notes": [
        "the metric name \"request_duration_seconds_bucket\" became a __name__ label matcher; LogQL selects streams by label only",
        "UNSUPPORTED: aggregation \"histogram_quantile\" is not available in logql"
      ],
      "ok": true,
      "output": "sum by (le) (rate({__name__=\"request_duration_seconds_bucket\"}[5m]))",
      "report": {
        "full": 6,
        "nodes": [
          {
            "flag": "PARTIAL",
            "path": "Query",
            "reason": "NaN-as-sentinel semantics differ between promql and logql; absent-data handling may vary",
            "type": "Query"
          },
          {
            "flag": "UNSUPPORTED",
            "path": "Query.Pipeline[2].AggregationStage",
            "reason": "aggregation \"histogram_quantile\" is not available in logql",
            "type": "AggregationStage"
          }
        ],
        "partial": 1,
        "score": 0.75,
        "signalMismatch": "query is METRIC, target supports LOG",
        "summary": "8 nodes: 6 full, 1 partial, 1 unsupported (score: 0.75)",
        "total": 8,
        "unsupported": 1,
        "worstFlag": "UNSUPPORTED",
        "worstReason": "aggregation \"histogram_quantile\" is not available in logql"
      },
      "text": "# the metric name \"request_duration_seconds_bucket\" became a __name__ label matcher; LogQL selects streams by label only\n# UNSUPPORTED: aggregation \"histogram_quantile\" is not available in logql\nsum by (le) (rate({__name__=\"request_duration_seconds_bucket\"}[5m]))"
    }
  },
  {
    "title": "Offset with no range",
    "note": "LogQL hangs an offset on a range and has no bare instant vector.",
    "source": "promql",
    "target": "logql",
    "query": "http_requests_total offset 1h",
    "result": {
      "notes": [
        "the metric name \"http_requests_total\" became a __name__ label matcher; LogQL selects streams by label only",
        "UNSUPPORTED: LogQL attaches an offset to a range, and this query has none; the 1h offset was dropped, so the result covers the caller's own time range rather than one shifted back by it"
      ],
      "ok": true,
      "output": "{__name__=\"http_requests_total\"}",
      "report": {
        "full": 2,
        "nodes": [
          {
            "flag": "PARTIAL",
            "path": "Query",
            "reason": "NaN-as-sentinel semantics differ between promql and logql; absent-data handling may vary",
            "type": "Query"
          },
          {
            "flag": "UNSUPPORTED",
            "path": "Query.Output.Window",
            "reason": "logql attaches an offset to a range, and this query has none; the 1h offset cannot be written, so the result would cover the caller's own time range rather than one shifted back by it",
            "type": "Window"
          }
        ],
        "partial": 1,
        "score": 0.5,
        "signalMismatch": "query is METRIC, target supports LOG",
        "summary": "4 nodes: 2 full, 1 partial, 1 unsupported (score: 0.50)",
        "total": 4,
        "unsupported": 1,
        "worstFlag": "UNSUPPORTED",
        "worstReason": "logql attaches an offset to a range, and this query has none; the 1h offset cannot be written, so the result would cover the caller's own time range rather than one shifted back by it"
      },
      "text": "# the metric name \"http_requests_total\" became a __name__ label matcher; LogQL selects streams by label only\n# UNSUPPORTED: LogQL attaches an offset to a range, and this query has none; the 1h offset was dropped, so the result covers the caller's own time range rather than one shifted back by it\n{__name__=\"http_requests_total\"}"
    }
  },
  {
    "title": "Log lines to a metric",
    "note": "The line filter has nowhere to go in PromQL; the aggregation survives.",
    "source": "logql",
    "target": "promql",
    "query": "sum by (level) (rate({app=\"api\"} |= \"error\" [5m]))",
    "result": {
      "notes": [
        "UNSUPPORTED: PromQL cannot filter on \"body\" at this point in the pipeline; only a series selector may filter on labels"
      ],
      "ok": true,
      "output": "sum by (level) (rate({app=\"api\"}[5m]))",
      "report": {
        "full": 9,
        "nodes": [
          {
            "flag": "PARTIAL",
            "path": "Query",
            "reason": "NaN-as-sentinel semantics differ between logql and promql; absent-data handling may vary",
            "type": "Query"
          },
          {
            "flag": "UNSUPPORTED",
            "path": "Query.Pipeline[0].FilterStage.Predicate",
            "reason": "promql has no log body to filter on; the filter cannot be written at all",
            "type": "MatchPredicate"
          }
        ],
        "partial": 1,
        "score": 0.8181818181818182,
        "signalMismatch": "query is LOG, target supports METRIC",
        "summary": "11 nodes: 9 full, 1 partial, 1 unsupported (score: 0.82)",
        "total": 11,
        "unsupported": 1,
        "worstFlag": "UNSUPPORTED",
        "worstReason": "promql has no log body to filter on; the filter cannot be written at all"
      },
      "text": "# UNSUPPORTED: PromQL cannot filter on \"body\" at this point in the pipeline; only a series selector may filter on labels\nsum by (level) (rate({app=\"api\"}[5m]))"
    }
  },
  {
    "title": "Span attributes to streams",
    "note": "Scoped attributes folded onto LogQL's one flat namespace.",
    "source": "traceql",
    "target": "logql",
    "query": "{resource.service.name = \"web\" \u0026\u0026 span.http.method = \"GET\"}",
    "result": {
      "notes": [
        "PARTIAL: LogQL label names admit no dots, so \"resource.service.name\" was written as \"resource_service_name\"",
        "PARTIAL: LogQL label names admit no dots, so \"span.http.method\" was written as \"span_http_method\""
      ],
      "ok": true,
      "output": "{resource_service_name=\"web\", span_http_method=\"GET\"}",
      "report": {
        "full": 7,
        "nodes": [
          {
            "flag": "PARTIAL",
            "path": "Query.Source.Spanset.Filters.Operands[0]",
            "reason": "logql has one flat label namespace and admits no dot in a name, so the scoped attribute \"resource.service.name\" becomes \"resource_service_name\"",
            "type": "MatchPredicate"
          },
          {
            "flag": "PARTIAL",
            "path": "Query.Source.Spanset.Filters.Operands[1]",
            "reason": "logql has one flat label namespace and admits no dot in a name, so the scoped attribute \"span.http.method\" becomes \"span_http_method\"",
            "type": "MatchPredicate"
          }
        ],
        "partial": 2,
        "score": 0.7777777777777778,
        "signalMismatch": "query is SPAN, target supports LOG",
        "summary": "9 nodes: 7 full, 2 partial, 0 unsupported (score: 0.78)",
        "total": 9,
        "unsupported": 0,
        "worstFlag": "PARTIAL",
        "worstReason": "logql has one flat label namespace and admits no dot in a name, so the scoped attribute \"resource.service.name\" becomes \"resource_service_name\""
      },
      "text": "# PARTIAL: LogQL label names admit no dots, so \"resource.service.name\" was written as \"resource_service_name\"\n# PARTIAL: LogQL label names admit no dots, so \"span.http.method\" was written as \"span_http_method\"\n{resource_service_name=\"web\", span_http_method=\"GET\"}"
    }
  },
  {
    "title": "A comparison the braces can't hold",
    "note": "Not droppable and not a selector matcher — it becomes a filter stage.",
    "source": "traceql",
    "target": "logql",
    "query": "{resource.service.name = \"web\" \u0026\u0026 duration \u003e 100ms}",
    "result": {
      "notes": [
        "PARTIAL: LogQL label names admit no dots, so \"resource.service.name\" was written as \"resource_service_name\""
      ],
      "ok": true,
      "output": "{resource_service_name=\"web\"} | duration \u003e 100ms",
      "report": {
        "full": 8,
        "nodes": [
          {
            "flag": "PARTIAL",
            "path": "Query.Source.Spanset.Filters.Operands[0]",
            "reason": "logql has one flat label namespace and admits no dot in a name, so the scoped attribute \"resource.service.name\" becomes \"resource_service_name\"",
            "type": "MatchPredicate"
          }
        ],
        "partial": 1,
        "score": 0.8888888888888888,
        "signalMismatch": "query is SPAN, target supports LOG",
        "summary": "9 nodes: 8 full, 1 partial, 0 unsupported (score: 0.89)",
        "total": 9,
        "unsupported": 0,
        "worstFlag": "PARTIAL",
        "worstReason": "logql has one flat label namespace and admits no dot in a name, so the scoped attribute \"resource.service.name\" becomes \"resource_service_name\""
      },
      "text": "# PARTIAL: LogQL label names admit no dots, so \"resource.service.name\" was written as \"resource_service_name\"\n{resource_service_name=\"web\"} | duration \u003e 100ms"
    }
  },
  {
    "title": "An OR that is set membership",
    "note": "Alternatives for one attribute are an IN, which both targets can write.",
    "source": "traceql",
    "target": "logql",
    "query": "{resource.service.name = \"web\" || resource.service.name = \"api\"}",
    "result": {
      "notes": [
        "PARTIAL: LogQL label names admit no dots, so \"resource.service.name\" was written as \"resource_service_name\""
      ],
      "ok": true,
      "output": "{resource_service_name=~\"web|api\"}",
      "report": {
        "full": 7,
        "nodes": [
          {
            "flag": "PARTIAL",
            "path": "Query.Source.Spanset.Filters.Operands[0]",
            "reason": "logql has one flat label namespace and admits no dot in a name, so the scoped attribute \"resource.service.name\" becomes \"resource_service_name\"",
            "type": "MatchPredicate"
          },
          {
            "flag": "PARTIAL",
            "path": "Query.Source.Spanset.Filters.Operands[1]",
            "reason": "logql has one flat label namespace and admits no dot in a name, so the scoped attribute \"resource.service.name\" becomes \"resource_service_name\"",
            "type": "MatchPredicate"
          }
        ],
        "partial": 2,
        "score": 0.7777777777777778,
        "signalMismatch": "query is SPAN, target supports LOG",
        "summary": "9 nodes: 7 full, 2 partial, 0 unsupported (score: 0.78)",
        "total": 9,
        "unsupported": 0,
        "worstFlag": "PARTIAL",
        "worstReason": "logql has one flat label namespace and admits no dot in a name, so the scoped attribute \"resource.service.name\" becomes \"resource_service_name\""
      },
      "text": "# PARTIAL: LogQL label names admit no dots, so \"resource.service.name\" was written as \"resource_service_name\"\n{resource_service_name=~\"web|api\"}"
    }
  },
  {
    "title": "A trace-tree relationship",
    "note": "No log or metric query records which record is whose parent.",
    "source": "traceql",
    "target": "logql",
    "query": "{resource.service.name = \"web\"} \u003e\u003e {status = error}",
    "result": {
      "notes": [
        "PARTIAL: LogQL label names admit no dots, so \"resource.service.name\" was written as \"resource_service_name\"",
        "UNSUPPORTED: logql has no way to relate records by their position in a trace; the descendant relationship cannot be written"
      ],
      "ok": true,
      "output": "{resource_service_name=\"web\"}",
      "report": {
        "full": 11,
        "nodes": [
          {
            "flag": "PARTIAL",
            "path": "Query.Source.Spanset.Filters",
            "reason": "logql has one flat label namespace and admits no dot in a name, so the scoped attribute \"resource.service.name\" becomes \"resource_service_name\"",
            "type": "MatchPredicate"
          },
          {
            "flag": "UNSUPPORTED",
            "path": "Query.Pipeline[0].StructuralStage",
            "reason": "logql has no way to relate records by their position in a trace; the descendant relationship cannot be written",
            "type": "StructuralStage"
          }
        ],
        "partial": 1,
        "score": 0.8461538461538461,
        "signalMismatch": "query is SPAN, target supports LOG",
        "summary": "13 nodes: 11 full, 1 partial, 1 unsupported (score: 0.85)",
        "total": 13,
        "unsupported": 1,
        "worstFlag": "UNSUPPORTED",
        "worstReason": "logql has no way to relate records by their position in a trace; the descendant relationship cannot be written"
      },
      "text": "# PARTIAL: LogQL label names admit no dots, so \"resource.service.name\" was written as \"resource_service_name\"\n# UNSUPPORTED: logql has no way to relate records by their position in a trace; the descendant relationship cannot be written\n{resource_service_name=\"web\"}"
    }
  }
];
